base_url = "https://pressingthumbs.com"
title = "Pressing Thumbs"
description = "A game development studio based in Berlin"
compile_sass = true
build_search_index = false
theme = "hyde"

[markdown]
highlight_code = false

[extra]
hyde_sticky = false
hyde_favicon = true
hyde_theme = "theme-base-0g"
hyde_links = [
    {name = "HOME", url = "/about"},
    {name = "TIMES OF PROGRESS", url = "/times-of-progress"},
    {name = "NEWSLETTER", url = "https://subscribepage.io/pressingthumbs"},
    {name = "CONTACTS", url = "/contacts"},
]
logo_path = "/logo_with_text.png"